(student/06-writing-proposal): clarify and link formal rules
google/gsocguides pull request #83
Opened 2022-03-23 14:31 UTC by kevinnls

the portion about "visa" is a bit ambiguous for
GSoC 2022, where general public contributors are
welcomed.

patch to clarify that and also link to official rules

2022-03-23 18:29 UTC, rspier requested changes
Thanks!

2022-03-23 18:55 UTC, kevinnls commented on pages/student/06-writing_a_proposal.md
> +First and foremost, make sure you meet [Google's formal requirements][rules] for participation in Summer of Code. Also, if you are studying overseas, ensure that you are eligible to participate in a
i had been wondering the same

hmmm, taking inspiration from the official [rules][1]
> for the duration of the Program, be eligible to work in the country in which they reside; and

what do you think of changing the entire line to
> Additionally, ensure that you are eligible to work in the country where you reside for the duration of the program.

[1]: https://summerofcode.withgoogle.com/rules#:~:text=for%20the%20duration%20of%20the%20Program%2C%20be%20eligible%20to%20work%20in%20the%20country%20in%20which%20they%20reside%3B%20and

2022-03-28 20:43 UTC, rspier commented on pages/student/06-writing_a_proposal.md
> +First and foremost, make sure you meet [Google's formal requirements][rules] for participation in Summer of Code. Also, if you are studying overseas, ensure that you are eligible to participate in a
I think that's clearer.

2022-03-28 21:56 UTC, kevinnls commented
look good?

2022-03-29 00:02 UTC, rspier approved these changes

2022-03-29 00:06 UTC, merged

2022-03-29 00:06 UTC, rspier commented
Looks good.